const plugin = require('tailwindcss/plugin')
const theme = require('tailwindcss/defaultTheme')

module.exports = {
   content: ['./src/**/*.{html,css,js,hbs,json}'],
   safelist: [],
   theme: {
      screens: {
         'min-xs': { min: '481px' },
         'min-sm': { min: '769px' },
         'min-md': { min: '1025px' },
         'min-lg': { min: '1281px' },
         'min-xl': { min: '1441px' },
         'min-2xl': { min: '1681px' },
         '2xl': { max: '1680px' },
         xl: { max: '1440px' },
         lg: { max: '1280px' },
         md: { max: '1024px' },
         sm: { max: '768px' },
         xs: { max: '480px' },
      },
      fontFamily: {
         primary: ['"Gilroy"', 'sans-serif'],
      },
      colors: { emerald: null, indigo: null, yellow: null, amber: null, red: null, orange: null, lime: null, green: null, teal: null, sky: null, cyan: null, blue: null, violet: null, purple: null, fuchsia: null, pink: null, slate: null, gray: null, zinc: null, neutral: null, stone: null, rose: null },
      extend: {
         colors: {
            transparent: 'transparent',
            current: 'currentColor',
            textColor: '#000000',
            bodyColor: '#FFFFFF',
            white: '#FFFFFF',
            black: '#000000',
            red: '#FF0000',
            main: {
               100: '#e2d1d1',
               200: '#c5a2a2',
               300: '#a87474',
               400: '#8b4545',
               500: '#6e1717',
               600: '#581212',
               700: '#420e0e',
               800: '#2c0909',
               900: '#160505',
            },
            primary: '#133E87',
            primaryDark: '#0D2A5E',
            primaryLight: '#1E5AC7',
            smokeWhite: '#F5F7FA',
            basicGray: '#EAEDED',
            light: '#E0E5EC',
            basicBlack: '#1A1A1A',
            ornage: '#FF9800',
            green: '#4CAF50',
            greenLight: '#27AE60',
         },
         aspectRatio: {
            none: 'unset',
            auto: 'auto',
            square: '1 / 1',
            '16/9': '16 / 9',
            '16/10': '16 / 10',
            '5/4': '5 / 4',
         },
         fontSize: (theme) => ({ ...theme('spacing') }),
         borderRadius: (theme) => ({ ...theme('spacing') }),
         borderWidth: (theme) => ({ ...theme('spacing') }),
         gridTemplateColumns: { '1/11': 'minmax(0,1fr) minmax(0,11fr)', '2/10': 'minmax(0,2fr) minmax(0,10fr)', '3/9': 'minmax(0,3fr) minmax(0,9fr)', '4/8': 'minmax(0,4fr) minmax(0,8fr)', '5/7': 'minmax(0,5fr) minmax(0,7fr)', '7/5': 'minmax(0,7fr) minmax(0,5fr)', '8/4': 'minmax(0,8fr) minmax(0,4fr)', '9/3': 'minmax(0,9fr) minmax(0,3fr)', '10/2': 'minmax(0,10fr) minmax(0,2fr)', '11/1': 'minmax(0,11fr) minmax(0,1fr)' },
         opacity: { 1: '0.01', 2: '0.02', 3: '0.03', 4: '0.04', 5: '0.05', 6: '0.06', 7: '0.07', 8: '0.08', 9: '0.09', 10: '0.10', 11: '0.11', 12: '0.12', 13: '0.13', 14: '0.14', 15: '0.15', 16: '0.16', 17: '0.17', 18: '0.18', 19: '0.19', 20: '0.20', 21: '0.21', 22: '0.22', 23: '0.23', 24: '0.24', 25: '0.25', 26: '0.26', 27: '0.27', 28: '0.28', 29: '0.29', 30: '0.30', 31: '0.31', 32: '0.32', 33: '0.33', 34: '0.34', 35: '0.35', 36: '0.36', 37: '0.37', 38: '0.38', 39: '0.39', 40: '0.40', 41: '0.41', 42: '0.42', 43: '0.43', 44: '0.44', 45: '0.45', 46: '0.46', 47: '0.47', 48: '0.48', 49: '0.49', 50: '0.50', 51: '0.51', 52: '0.52', 53: '0.53', 54: '0.54', 55: '0.55', 56: '0.56', 57: '0.57', 58: '0.58', 59: '0.59', 60: '0.60', 61: '0.61', 62: '0.62', 63: '0.63', 64: '0.64', 65: '0.65', 66: '0.66', 67: '0.67', 68: '0.68', 69: '0.69', 70: '0.70', 71: '0.71', 72: '0.72', 73: '0.73', 74: '0.74', 75: '0.75', 76: '0.76', 77: '0.77', 78: '0.78', 79: '0.79', 80: '0.80', 81: '0.81', 82: '0.82', 83: '0.83', 84: '0.84', 85: '0.85', 86: '0.86', 87: '0.87', 88: '0.88', 89: '0.89', 90: '0.90', 91: '0.91', 92: '0.92', 93: '0.93', 94: '0.94', 95: '0.95', 96: '0.96', 97: '0.97', 98: '0.98', 99: '0.99', 100: '1' },
         scale: { 115: '1.15', 175: '1.75', 180: '1.80', 185: '1.85', 190: '1.90', 200: '2', 300: '3', 400: '4', 500: '5' },
         transitionDuration: { 0: '0ms', 250: '250ms', 350: '350ms', 450: '450ms', 600: '600ms', 750: '750ms' },
         transitionDelay: { 250: '250ms', 350: '350ms', 450: '450ms', 600: '600ms', 750: '750ms' },
         zIndex: { 1: '1', 2: '2', 3: '3', 4: '4', 5: '5', 6: '6', 7: '7', 8: '8', 9: '9', 9: '9', 60: '60', 70: '70', 80: '80', 90: '90', 100: '100' },
         transitionTimingFunction: {
            pentalogo: 'cubic-bezier(0.77,0,0.175,1)',
            manidar: 'cubic-bezier(.77,.16,.09,.94)',
            kagitmiadam: 'cubic-bezier(.42,.97,.52,1.49)',
         },
         keyframes: {
            ripple: { '0%': { opacity: '0', transform: 'scale(0.9)' }, '1%': { opacity: '1', transform: 'scale(0.9)' }, '50%': { opacity: '1', transform: 'scale(1.9)' }, '100%': { opacity: '0', transform: 'scale(2.9)' } },
            py: { from: { transform: 'scale(0.85) rotateY(0deg) translateZ(0) translate3d(0,0,0) perspective(1px)' }, to: { transform: 'scale(0.85) rotateY(-360deg) translateZ(0) translate3d(0,0,0) perspective(1px)' } },
         },
         animation: {
            'ripple-first': 'ripple 2s linear infinite',
            'ripple-second': 'ripple 2s linear 1s infinite',
            py: 'py 2s linear infinite',
         },
         typography: (theme) => ({
            DEFAULT: {
               css: {
                  maxWidth: 'none',
                  h1: {
                     marginTop: '0!important',
                     marginBottom: '0!important',
                     fontSize: '3.375rem',
                     lineHeight: '1!important',
                     fontWeight: '400',
                     color: theme('colors.textColor'),
                  },
                  h2: {
                     marginTop: '0!important',
                     marginBottom: '0!important',
                     fontSize: '3rem',
                     lineHeight: '1!important',
                     fontWeight: '400',
                     color: theme('colors.textColor'),
                  },
                  h3: {
                     marginTop: '0!important',
                     marginBottom: '0!important',
                     fontSize: '2.625rem',
                     lineHeight: '1.125!important',
                     fontWeight: '400',
                     color: theme('colors.textColor'),
                  },
                  h4: {
                     marginTop: '0!important',
                     marginBottom: '0!important',
                     fontSize: '2.25rem',
                     lineHeight: '1.25!important',
                     fontWeight: '400',
                     color: theme('colors.textColor'),
                  },
                  h5: {
                     marginTop: '0!important',
                     marginBottom: '0!important',
                     fontSize: '2rem',
                     lineHeight: '1.5!important',
                     fontWeight: '400',
                     color: theme('colors.textColor'),
                  },
                  h6: {
                     marginTop: '0!important',
                     marginBottom: '0!important',
                     fontSize: '1.5rem',
                     lineHeight: '1.5!important',
                     fontWeight: '400',
                     color: theme('colors.textColor'),
                  },
                  p: {
                     marginTop: '0!important',
                     marginBottom: '0!important',
                     fontSize: '1.125rem',
                     lineHeight: '1.5!important',
                     color: theme('colors.textColor'),
                  },
                  a: {
                     marginTop: '0!important',
                     marginBottom: '0!important',
                     fontSize: '1.125rem',
                     lineHeight: '1.5!important',
                     textDecoration: 'none',
                     position: 'relative',
                     display: 'inline-block',
                     transition: 'color 0.2s',
                     color: theme('colors.main-500'),
                     '&:hover': {
                        '&:before': {
                           width: '100%',
                        },
                     },
                     '&:before': {
                        content: '""',
                        position: 'absolute',
                        left: '0',
                        bottom: '0',
                        display: 'block',
                        height: '2px',
                        width: '0',
                        backgroundColor: theme('colors.main-500'),
                        transition: 'width 0.2s',
                     },
                  },
                  ul: {
                     marginTop: '0!important',
                     marginBottom: '0!important',
                     display: 'flex',
                     flexDirection: 'column',
                     gap: '1rem',
                     color: theme('colors.textColor'),
                  },
                  ol: {
                     marginTop: '0!important',
                     marginBottom: '0!important',
                     display: 'flex',
                     flexDirection: 'column',
                     gap: '1rem',
                     color: theme('colors.textColor'),
                  },
                  li: {
                     marginTop: '0!important',
                     marginBottom: '0!important',
                     fontSize: '1.125rem',
                     lineHeight: '1.5!important',
                     paddingLeft: '0!important',
                     color: theme('colors.textColor'),
                     '&::marker': {
                        color: 'inherit!important',
                     },
                  },
                  blockquote: {
                     marginTop: '0!important',
                     marginBottom: '0!important',
                     fontSize: '1.25rem',
                     lineHeight: '1.5!important',
                     color: theme('colors.textColor'),
                  },
                  hr: {
                     marginTop: '0!important',
                     marginBottom: '0!important',
                     backgroundColor: 'rgba(0, 0, 0, 0.1)',
                     border: 'none',
                     height: '1px',
                     width: '100%',
                  },
               },
            },
            white: {
               css: {
                  color: '#FFFFFF',
                  h1: { color: '#FFFFFF' },
                  h2: { color: '#FFFFFF' },
                  h3: { color: '#FFFFFF' },
                  h4: { color: '#FFFFFF' },
                  h5: { color: '#FFFFFF' },
                  h6: { color: '#FFFFFF' },
                  p: { color: '#FFFFFF' },
                  li: { color: '#FFFFFF' },
                  blockquote: { color: '#FFFFFF' },
                  hr: { background: 'rgba(255, 255, 255, 0.1)' },
               },
            },
            '2xl': {
               css: {
                  h1: { fontSize: '3rem' },
                  h2: { fontSize: '2.625rem' },
                  h3: { fontSize: '2.25rem' },
                  h4: { fontSize: '2rem' },
                  h5: { fontSize: '1.5rem' },
                  h6: { fontSize: '1.25rem' },
                  p: { fontSize: '1.125rem' },
                  a: { fontSize: '1.125rem' },
                  li: { fontSize: '1.125rem' },
                  blockquote: { fontSize: '1.25rem' },
               },
            },
            xl: {
               css: {
                  h1: { fontSize: '2.625rem' },
                  h2: { fontSize: '2.25rem' },
                  h3: { fontSize: '1.5rem' },
                  h4: { fontSize: '1.375rem' },
                  h5: { fontSize: '1.25rem' },
                  h6: { fontSize: '1.125rem' },
                  p: { fontSize: '1.125rem' },
                  a: { fontSize: '1.125rem' },
                  ul: { gap: '0.75rem' },
                  ol: { gap: '0.75rem' },
                  li: { fontSize: '1.125rem' },
                  blockquote: { fontSize: '1.125rem' },
               },
            },
            lg: {
               css: {
                  h1: { fontSize: '2.25rem' },
                  h2: { fontSize: '2rem' },
                  h3: { fontSize: '1.5rem' },
                  h4: { fontSize: '1.25rem' },
                  h5: { fontSize: '1.125rem' },
                  h6: { fontSize: '1rem' },
                  p: { fontSize: '1rem' },
                  a: { fontSize: '1rem' },
                  li: { fontSize: '1rem' },
                  blockquote: { fontSize: '1.125rem' },
               },
            },
            md: {
               css: {
                  h1: { fontSize: '2rem' },
                  h2: { fontSize: '1.5rem' },
                  h3: { fontSize: '1.25rem' },
                  h4: { fontSize: '1.125rem' },
                  h5: { fontSize: '1rem' },
                  h6: { fontSize: '0.875rem' },
                  p: { fontSize: '0.875rem' },
                  a: { fontSize: '0.875rem' },
                  ul: { gap: '0.5rem' },
                  ol: { gap: '0.5rem' },
                  li: { fontSize: '0.875rem' },
                  blockquote: { fontSize: '1rem' },
               },
            },
            sm: {
               css: {
                  h1: { fontSize: '2rem' },
                  h2: { fontSize: '1.5rem' },
                  h3: { fontSize: '1.25rem' },
                  h4: { fontSize: '1.125rem' },
                  h5: { fontSize: '1rem' },
                  h6: { fontSize: '0.875rem' },
                  p: { fontSize: '0.875rem' },
                  a: { fontSize: '0.875rem' },
                  ul: { gap: '0.25rem' },
                  ol: { gap: '0.25rem' },
                  li: { fontSize: '0.875rem' },
                  blockquote: { fontSize: '1rem' },
               },
            },
            xs: {
               css: {
                  h1: { fontSize: '2rem' },
                  h2: { fontSize: '1.5rem' },
                  h3: { fontSize: '1.25rem' },
                  h4: { fontSize: '1.125rem' },
                  h5: { fontSize: '1rem' },
                  h6: { fontSize: '0.875rem' },
                  p: { fontSize: '0.875rem' },
                  a: { fontSize: '0.875rem' },
                  li: { fontSize: '0.875rem' },
                  blockquote: { fontSize: '1rem' },
               },
            },
         }),
      },
   },
   plugins: [
      require('@tailwindcss/typography')({ className: 'text-editor' }),
      require('@igorkowalczyk/is-browser'),
      require('tailwind-scrollbar')({ nocompatible: true, preferredStrategy: 'pseudoelements' }),
      plugin(function ({ addUtilities, matchUtilities, theme }) {
         matchUtilities(
            {
               'translate-z': (value) => ({ '--tw-translate-z': value, transform: ` translate3d(var(--tw-translate-x), var(--tw-translate-y), var(--tw-translate-z)) rotate(var(--tw-rotate)) skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y)) scaleX(var(--tw-scale-x)) scaleY(var(--tw-scale-y))` }),
            },
            {
               values: theme('translate'),
               supportsNegativeValues: true,
            },
         ),
            addUtilities({
               /* Additional Classes */
               '.font-heavy': { 'font-weight': '1000' },
               '.text-fill-transparent': { '-webkit-text-fill-color': 'transparent' },
               '.transform-fill': { 'transform-box': 'fill-box' },
               '.transform-flat': { 'transform-style': 'flat' },
               '.transform-3d': { 'transform-style': 'preserve-3d' },
               '.backface-hidden': { 'backface-visibility': 'hidden' },
               '.backface-visible': { 'backface-visibility': 'visible' },
               '.writing-vertical-rl': { 'writing-mode': 'vertical-rl' },
               '.text-orientation-mixed': { 'text-orientation': 'mixed' },
               /* Custom Classes */
               '.overflow-fix': { 'mask-image': '-webkit-radial-gradient(white,_black)' },
               '.full-cover': { width: '100%', height: '100%', 'object-fit': 'cover', 'object-position': 'center', display: 'block' },
               '.full-contain': { width: '100%', height: '100%', 'object-fit': 'contain', 'object-position': 'center', display: 'block' },
               '.fixed-full': { position: 'fixed', top: '0', left: '0', width: '100%', height: '100%' },
               '.absolute-full': { position: 'absolute', top: '0', left: '0', width: '100%', height: '100%' },
               '.absolute-center': { position: 'absolute', top: '50%', left: '50%', transform: 'translate(-50%, -50%)' },
               '.flex-center': { display: 'flex', 'justify-content': 'center', 'align-items': 'center' },
               '.before-full:before': { content: '""', position: 'absolute', top: '0', left: '0', width: '100%', height: '100%' },
               '.after-full:after': { content: '""', position: 'absolute', top: '0', left: '0', width: '100%', height: '100%' },
               '.line-clamp': { overflow: 'hidden', 'text-overflow': 'ellipsis', 'white-space': 'nowrap', 'max-width': '100%' },
            })
      }),
   ],
}
